title: Manuel J. Tejada
email: manute32@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Designer & Front-End Web Developer from the Dominican Republic
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manueljtejada.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: manueljtejada
github_username:  manueljtejada

collections:
  portfolio:
    title: Portfolio
    output: false

# Build settings
markdown: kramdown
permalink: date
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - bower_components
sass:
    sass_dir: _sass
