---
title: Manuel J. Tejada
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: manute32@gmail.com
description: 'Web Designer & Front-End Web Developer from the Dominican Republic

'
baseurl: ''
url: http://manueljtejada.com
twitter_username: manueljtejada
github_username: manueljtejada
markdown: kramdown
permalink: date
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- vendor
- bower_components
sass:
  sass_dir: _sass
